### ISSUE TITLE
Add ZeroMQ Pub/Sub as Integration Option

### ISSUE THREAD

**Issue by casey-boyer-spoke** [brocaar/chirpstack-gateway-bridge#202]
> I created this in the wrong account... moved to: #203

- [x] I have searched the [issues](https://github.com/brocaar/chirpstack-gateway-bridge) of this repository and believe that this is not a duplicate.

## What is the use-case?

I'm in the process of deploying a full LoRa stack at the edge. We already have an MQTT**S** broker at the edge, but it would be a hassle to configure this bridge to access that broker (certificate generation and dissemination at scale would be more of a hassle than it's worth). I'd also like to avoid having two brokers on the same server as all I need is a means to forward packets to the local Network Server.

## Implementation description

Example concept configuration:
```toml
# Integration configuration.
[integration]
type="zmq"
# Payload marshaler.
#
# This defines how the MQTT payloads are encoded. Valid options are:
# * protobuf:  Protobuf encoding
# * json:      JSON encoding (easier for debugging, but less compact than 'protobuf')
marshaler="protobuf"

  # ZMQ integration configuration.
  [integration.zmq]
  event_url="ipc:///tmp/gatewaybridge_event"
  command_url="ipc:///tmp/gatewaybridge_command"
```

## Can you implement this by yourself and make a pull request?

I intend to implement and create a PR myself assuming it's welcomed. I would also be creating a complementary PR in the `chirpstack-network-server` repository implementing the other side of this integration.
